services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seti_tests
    environment:
      - PYTHONPATH=/app

  stage1_demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seti_stage1_demo
    command: ["python", "demo_stage1.py"]
    environment:
      - PYTHONPATH=/app

  stage2_demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seti_stage2_demo
    command: ["python", "demo_stage2.py"]
    environment:
      - PYTHONPATH=/app